# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Maven build
      run: mvn -B verify -Dquarkus.container-image.build=true
    - name: SonarQube verification
      run: |
        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=marcelstoer-github \
            -Dsonar.projectKey=com.frightanic:open-data-smn
    - name: Prepare artifacts staging
      run: mkdir staging && cp -r target/*.jar target/quarkus-app staging
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
